#if defined _rc_console_variable_included
 #endinput
#endif
#define _rc_console_variable_included

enum {
    CvarLimit_Min,
    CvarLimit_Max,

    CvarLimit_Amount
};

enum {
    Cvar_InterpMin,
    Cvar_InterpMax,
    Cvar_InterpRatioMin,
    Cvar_InterpRatioMax,
    Cvar_CmdRateMin,
    Cvar_CmdRateMax,
    Cvar_UpdateRateMin,
    Cvar_UpdateRateMax,
    Cvar_RateMin,
    Cvar_RateMax,

    Cvar_Amount
};
