#if defined _rc_console_variable_included
 #endinput
#endif
#define _rc_console_variable_included

#define CONSOLE_VARIABLE_MAX_SIZE 16
#define CONSOLE_VARIABLE_UNDEFINED ""

#define CONSOLE_VARIABLE_INTERP "cl_interp"
#define CONSOLE_VARIABLE_INTERP_RATIO "cl_interp_ratio"
#define CONSOLE_VARIABLE_CMD_RATE "cl_cmdrate"
#define CONSOLE_VARIABLE_UPDATE_RATE "cl_updaterate"
#define CONSOLE_VARIABLE_RATE "rate"
