#if defined _rc_console_variable_included
 #endinput
#endif
#define _rc_console_variable_included

#define VARIABLE_MAX_SIZE 16
#define VARIABLE_UNDEFINED ""

#define VARIABLE_INTERP "cl_interp"
#define VARIABLE_INTERP_RATIO "cl_interp_ratio"
#define VARIABLE_CMD_RATE "cl_cmdrate"
#define VARIABLE_UPDATE_RATE "cl_updaterate"
#define VARIABLE_RATE "rate"

#define MIN_VALUE_YES true
#define MIN_VALUE_NO false
