#if defined _rc_menu_included
 #endinput
#endif
#define _rc_menu_included

#define TITLE_SIZE (64 * 4)

#define INFO_SIZE 16
#define ITEM_SIZE 32

#define TITLE_RATES_CHECKER "Rates checker"
#define TITLE_PLAYER_RATES "Player rates"

#define ITEM_PLAYER_PREV "Previous player"
#define ITEM_PLAYER_NEXT "Next player"
#define ITEM_BACK "Back"
#define ITEM_EXIT "Exit"

#define KEY_PLAYER_PREV 7
#define KEY_PLAYER_NEXT 8
#define KEY_BACK 9
#define KEY_EXIT 10
