#if defined _rc_menu_included
 #endinput
#endif
#define _rc_menu_included

#define RATES_CHECKER "Rates checker"
#define PLAYER_RATES "Player rates"
#define SERVER_RATES "Server rates"
#define RATE_VALUE_GOOD "Rate value good"
#define RATE_VALUE_BAD "Rate value bad"
#define MINIMUM "Minimum"
#define MAXIMUM "Maximum"

#define PLAYER_NAME_MAX_SIZE (32 * 4 + 1)
#define USER_ID_MAX_SIZE 16
#define ITEM_MAX_SIZE (32 * 4 + 1)
